version: '3.1'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf
      - .nginx/mime.types:/etc/nginx/mime.types
      - ./src:/var/www/html